name:                dummy-app
version:             0.1.0.0
github:              "githubuser/dummy-app"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/dummy-app#readme>

dependencies:
- base >= 4.7 && < 5
- haskeline >=0.8.1.2
- bytestring
- zlib
- serialise
- cereal
- directory
- time
- mtl
- megaparsec
- parser-combinators
- text
- containers
- prettyprinter
- prettyprinter-ansi-terminal
- scientific



library:
  source-dirs: src

executables:
  dummy-app-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dummy-app